<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-25T12:12:33 IST" name="Suite" finished-at="2024-08-25T12:13:21 IST" duration-ms="47663">
    <groups>
      <group name="ErrorValidationTest">
        <method signature="Luma_ErrorValidation_Test.Luma_checkLoginError(java.util.HashMap)[pri:0, instance:Luma_Test.tests.Luma_ErrorValidation_Test@7ca20101]" name="Luma_checkLoginError" class="Luma_Test.tests.Luma_ErrorValidation_Test"/>
        <method signature="Luma_ErrorValidation_Test.productValidation(java.util.HashMap)[pri:0, instance:Luma_Test.tests.Luma_ErrorValidation_Test@7ca20101]" name="productValidation" class="Luma_Test.tests.Luma_ErrorValidation_Test"/>
      </group> <!-- ErrorValidationTest -->
    </groups>
    <test started-at="2024-08-25T12:12:33 IST" name="Chek LoginErrorValidationMessage Of Products and Ordered Product" finished-at="2024-08-25T12:13:21 IST" duration-ms="47663">
      <class name="Luma_Test.tests.Luma_ErrorValidation_Test">
        <test-method is-config="true" signature="launchWebURLDriver()[pri:0, instance:Luma_Test.tests.Luma_ErrorValidation_Test@7ca20101]" started-at="2024-08-25T12:12:33 IST" name="launchWebURLDriver" finished-at="2024-08-25T12:12:45 IST" duration-ms="11448" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchWebURLDriver -->
        <test-method signature="Luma_checkLoginError(java.util.HashMap)[pri:0, instance:Luma_Test.tests.Luma_ErrorValidation_Test@7ca20101]" started-at="2024-08-25T12:12:45 IST" name="Luma_checkLoginError" data-provider="get_LoginError_TestData" finished-at="2024-08-25T12:12:48 IST" duration-ms="2603" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{loginErrorMessage=The account sign-in was or your account is disabled temporarily. Please wait and try again later., password=King@123452367890, userName=s123@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.] but found [The account sign-in was or your account is disabled temporarily. Please wait and try again later.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.] but found [The account sign-in was or your account is disabled temporarily. Please wait and try again later.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Luma_Test.tests.Luma_ErrorValidation_Test.Luma_checkLoginError(Luma_ErrorValidation_Test.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Luma_checkLoginError -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:Luma_Test.tests.Luma_ErrorValidation_Test@7ca20101]" started-at="2024-08-25T12:12:48 IST" name="closeDriver" finished-at="2024-08-25T12:12:48 IST" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method is-config="true" signature="launchWebURLDriver()[pri:0, instance:Luma_Test.tests.Luma_ErrorValidation_Test@7ca20101]" started-at="2024-08-25T12:12:48 IST" name="launchWebURLDriver" finished-at="2024-08-25T12:12:57 IST" duration-ms="9369" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchWebURLDriver -->
        <test-method signature="productValidation(java.util.HashMap)[pri:0, instance:Luma_Test.tests.Luma_ErrorValidation_Test@7ca20101]" started-at="2024-08-25T12:12:57 IST" name="productValidation" data-provider="get_ValidateOrderedProducts_TestData" finished-at="2024-08-25T12:13:21 IST" duration-ms="23557" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{productToSelect=Grayson Crewneck Sweatshirt, password=King@12345, colorToSelect=Red, userName=Kshirish123@gmail.com, quantityToSelect=2}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productValidation -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:Luma_Test.tests.Luma_ErrorValidation_Test@7ca20101]" started-at="2024-08-25T12:13:21 IST" name="closeDriver" finished-at="2024-08-25T12:13:21 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- Luma_Test.tests.Luma_ErrorValidation_Test -->
    </test> <!-- Chek LoginErrorValidationMessage Of Products and Ordered Product -->
  </suite> <!-- Suite -->
</testng-results>
